/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lev-logo-3d.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lev-logo-3d.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.letter_L.geometry} material={materials.lev_white} position={[-2.7, -1.818, -0.16]} />
      <mesh geometry={nodes.letter_E.geometry} material={materials.lev_white} position={[-2.7, -1.818, -0.16]} />
      <mesh geometry={nodes.letter_V.geometry} material={materials.lev_white} position={[-2.7, -1.818, -0.16]} />
    </group>
  )
}

useGLTF.preload('/lev-logo-3d.glb')
